import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class Loc {
  static final ValueNotifier<Locale> localeNotifier = ValueNotifier(const Locale('en'));

  static bool get isArabic => localeNotifier.value.languageCode == 'ar';

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final lang = prefs.getString('language') ?? 'en';
    localeNotifier.value = Locale(lang);
  }

  static Future<void> toggleLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    if (isArabic) {
      localeNotifier.value = const Locale('en');
      await prefs.setString('language', 'en');
    } else {
      localeNotifier.value = const Locale('ar');
      await prefs.setString('language', 'ar');
    }
  }

  static String tr(String key) {
    if (isArabic) {
      return _ar[key] ?? key;
    }
    return key;
  }

  static final Map<String, String> _ar = {
    'Good Morning,': 'صباح الخير،',
    'Morning Ritual': 'طقوس الصباح',
    'Start your day right': 'ابدأ يومك بشكل صحيح',
    'Safe Journal': 'مذكرات آمنة',
    'Private thoughts': 'أفكار خاصة',
    'Diaries': 'مذكراتي',
    'Diary entry saved privately.': 'تم حفظ المذكرة بخصوصية.',
    'Diary Title': 'عنوان المذكرة',
    'Diary Library': 'مكتبة المذكرات',
    'Diary Access': 'الوصول للمذكرات',
    'Please enter your account password to open your private diary.': 'يرجى إدخال كلمة مرور حسابك لفتح مذكراتك الخاصة.',
    'ADHD Exercise': 'تمارين فرط الحركة',
    'Stay focused': 'حافظ على تركيزك',
    'Nightly Unwind': 'استرخاء مسائي',
    'Peaceful sleep': 'نوم هادئ',
    'Account Information': 'معلومات الحساب',
    'Security': 'الأمان',
    'Preferences': 'التفضيلات',
    'Notifications': 'الإشعارات',
    'Language': 'اللغة',
    'English': 'العربية',
    'Theme Mode': 'المظهر',
    'Light Mode': 'الوضع الفاتح',
    'Dark Mode': 'الوضع الداكن',
    'Safespace': 'سيف سبيس',
    'Settings': 'الإعدادات',
    'Home': 'الرئيسية',
    'Profile': 'الملف الشخصي',
    'Explore': 'استكشاف',
    'Wellness': 'الصحة',
    'Wellness Tools': 'أدوات الصحة',
    'My Profile': 'ملفي الشخصي',
    'Sign In': 'تسجيل الدخول',
    'Sign Up': 'إنشاء حساب',
    'Logout': 'تسجيل الخروج',
    'Login': 'تسجيل الدخول',
    'Cancel': 'إلغاء',
    'Save': 'حفظ',
    'Delete': 'حذف',
    'Edit Entry': 'تعديل',
    'Delete Entry': 'حذف',
    'Next': 'التالي',
    'Submit': 'إرسال',
    'Back to Home': 'العودة للرئيسية',
    'Goal Tracker': 'متتبع الأهداف',
    'Your Plan': 'خطتك',
    'Daily Check-ins': 'التقييم اليومي',
    'Add New Goal': 'إضافة هدف جديد',
    'No goals set yet. Add one!': 'لم يتم تعيين أهداف بعد. أضف واحداً!',
    'Mood Tracking': 'تتبع المزاج',
    'Mood Questionnaire': 'استبيان المزاج',
    'Take Assessment': 'بدء التقييم',
    'NLP Text Analysis': 'تحليل النص الذكي',
    'Analyze Text': 'تحليل النص',
    'Start Analysis': 'بدء التحليل',
    'Analysis Results': 'نتائج التحليل',
    'Crisis Support': 'دعم الأزمات',
    'Please Reach Out for Help': 'يرجى طلب المساعدة',
    'Your privacy is our priority. All data is analyzed securely.': 'خصوصيتك هي أولويتنا. يتم تحليل جميع البيانات بشكل آمن.',
    'How are you feeling right now?': 'كيف تشعر الآن؟',
    'How are you really doing?': 'كيف حالك حقاً؟',
    'How is your energy level today?': 'كيف هو مستوى طاقتك اليوم؟',
    'How stressed do you feel right now?': 'ما مدى التوتر الذي تشعر به الآن؟',
    'How well did you sleep last night?': 'كيف كان نومك الليلة الماضية؟',
    'Daily check-in completed!': 'تم التقييم اليومي بنجاح!',
    'You have already completed your check-in for today!': 'لقد قمت بإكمال التقييم اليومي الخاص بك لهذا اليوم!',
    'Journal Library': 'مكتبة المذكرات',
    'No entries yet': 'لا توجد مذكرات بعد',
    'Create Account': 'إنشاء حساب',
    'Already have an account?': 'لديك حساب بالفعل؟',
    'Forgot Password?': 'نسيت كلمة المرور؟',
    'Password reset link sent to your email': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
    'No email found to reset password.': 'لم يتم العثور على بريد إلكتروني.',
    'Type or speak your thoughts:': 'اكتب أو تحدث بأفكارك:',
    'Write in Arabic or English. The survey works better with longer sentences, so describe your feeling more fully.': 'اكتب باللغة العربية أو الإنجليزية. صف شعورك بالتفصيل.',
    'Based on your answers, here is your current emotional state profile:': 'بناءً على إجاباتك، هذا هو ملف حالتك العاطفية الحالي:',
    'Clinical Profile': 'الملف السريري',
    'Start Game': 'بدء اللعبة',
    'Play Again': 'العب مرة أخرى',
    'Game Over!': 'انتهت اللعبة!',
    'Bubble Pop': 'فرقعة الفقاعات',
    'Color Match': 'تطابق الألوان',
    'Box Breathing': 'تنفس الصندوق',
    'Meditation': 'التأمل',
    'Start Meditation': 'بدء التأمل',
    'Cancel Session': 'إلغاء الجلسة',
    'Meditation Complete': 'اكتمل التأمل',
    'Finish': 'إنهاء',
    'Set Your Duration': 'حدد المدة',
    'How many minutes would you like to meditate today?': 'كم دقيقة تود التأمل اليوم؟',
    'Breathe deeply and let go...': 'تنفس بعمق واسترخ...',
    'Take a deep breath.': 'خذ نفساً عميقاً.',
    'You have completed your session. You should feel more calm and centered now.': 'لقد أكملت جلستك. يجب أن تشعر بمزيد من الهدوء الآن.',
    '5-4-3-2-1 Grounding': 'تقنية التجذير 5-4-3-2-1',
    'ADHD Exercises': 'تمارين فرط الحركة',
    'Short, practical exercises to help you focus, reset, and build steady habits.': 'تمارين قصيرة وعملية لمساعدتك على التركيز.',
    'Practice 1 new skill': 'مارس مهارة جديدة واحدة',
    'Build - Every month': 'طوّر - كل شهر',
    'Read a Book': 'اقرأ كتاباً',
    'Pay your bills': 'ادفع فواتيرك',
    'Every month': 'كل شهر',
    'Clean up your Home': 'نظّف منزلك',
    'Every Week': 'كل أسبوع',
    'Message Someone you love': 'راسل شخصاً تحبه',
    'Every Day': 'كل يوم',
    'Exercise': 'مارس التمارين',
    'Time Of Day Recommendations': 'توصيات الوقت الحالي',
    'Morning Recommendations': 'توصيات الصباح',
    'Evening Recommendations': 'توصيات المساء',
    'Daily check-in': 'التقييم اليومي',
    'Question 1 of 3': 'السؤال 1 من 3',
    'Question 2 of 3': 'السؤال 2 من 3',
    'Question 3 of 3': 'السؤال 3 من 3',
    'Very Bad': 'سيئ جداً',
    'Bad': 'سيئ',
    'Neutral': 'محايد',
    'Good': 'جيد',
    'Excellent': 'ممتاز',
    '<4h': 'أقل من 4 ساعات',
    '4-5h': '4-5 ساعات',
    '5-6h': '5-6 ساعات',
    '6-7h': '6-7 ساعات',
    '8h+': '8 ساعات أو أكثر',
    'Low': 'منخفض',
    'Mid': 'متوسط',
    'High': 'مرتفع',
    'You feel great 😌': 'تشعر بحالة رائعة 😌',
    'You feel a bit down today.': 'تشعر ببعض الانخفاض اليوم.',
    'Your energy feels very low': 'طاقتك منخفضة جداً',
    'Your energy feels moderate': 'طاقتك متوسطة',
    'Your energy feels steady and positive.': 'طاقتك مستقرة وإيجابية.',
    'You got enough rest and woke up okay.': 'نمت بما يكفي واستيقظت بخير.',
    'You could use more rest tonight.': 'قد تحتاج إلى مزيد من الراحة الليلة.',
    'Good sleep': 'نوم جيد',
    'Inhale': 'شهيق',
    'Hold': 'ثبات',
    'Exhale': 'زفير',
    'Sunlight Exposure': 'التعرض لأشعة الشمس',
    'Healthy Breakfast': 'إفطار صحي',
    'Hydrate': 'اشرب الماء',
    'Digital Detox': 'الابتعاد عن الشاشات',
    'Warm Bath/Shower': 'حمام/دش دافئ',
    'Warm Tea': 'شاي دافئ',
    'Calm Breathing': 'تنفس هادئ',
    'Morning Journaling': 'كتابة صباحية',
    'Daily Intention': 'نية اليوم',
    'Mindful Coffee/Tea': 'قهوة/شاي بوعي',
    'Physical Movement': 'حركة بدنية',
    'Gentle Start': 'بداية هادئة',
    'Progressive Muscle Relaxation': 'إرخاء العضلات التدريجي',
    'Guided Grounding': 'تجذير موجّه',
    'White Noise / Nature Sounds': 'ضوضاء بيضاء / أصوات الطبيعة',
    'Positive Reflection': 'تأمل إيجابي',
    'Self-Compassion': 'الرحمة بالذات',
    'Focus Challenge': 'تحدي التركيز',
    'Follow the dot and synchronize your breath.': 'اتبع النقطة ونسق تنفسك.',
    'Tap the button that matches the FONT COLOR of the word, not what the word says!': 'انقر على الزر الذي يطابق لون الخط للكلمة!',
    'What is Box Breathing?': 'ما هو تنفس الصندوق؟',
    'Also known as four-square breathing, it is a simple technique used to reduce stress and improve focus. It involves breathing in, holding, breathing out, and holding again, each for an equal count of 4 seconds.': 'يُعرف أيضًا باسم التنفس المربع، وهو تقنية بسيطة لتقليل التوتر.',
    'DASS-42 Questionnaire': 'استبيان DASS-42',
    'Text + DASS-42': 'النص واستبيان DASS-42',
    'Full Assessment': 'التقييم الشامل',
    'Full Wellbeing Analysis': 'تحليل شامل للصحة',
    'A comprehensive look at your mental health using AI and clinical standards.': 'نظرة شاملة على صحتك النفسية.',
    'Answer all three questions in one place with a calm, quick survey flow.': 'أجب عن الأسئلة الثلاثة من خلال استبيان سريع.',
    'This assessment combines your written reflection with 42 questions. It helps you understand your mood patterns, not a medical diagnosis.': 'يجمع هذا التقييم بين كتاباتك و 42 سؤالاً لمساعدتك على فهم أنماط مزاجك.',
    'Please answer all questions': 'يرجى الإجابة على جميع الأسئلة',
    'Previous': 'السابق',
    'Your Assessment Results': 'نتائج التقييم الخاصة بك',
    'Normal': 'طبيعي',
    'Mild': 'خفيف',
    'Moderate': 'متوسط',
    'Severe': 'شديد',
    'Extremely Severe': 'شديد جداً',
    'What does this mean?': 'ماذا يعني هذا؟',
    'These scales measure the intensity of emotional states. They are not a clinical diagnosis but a way to help you understand your feelings better.': 'تقيس هذه المقاييس شدة الحالات العاطفية لمساعدتك على الفهم.',
    'These scores are raw probabilities from the NLP text model. A higher percentage indicates stronger semantic correlation with the condition.': 'هذه الدرجات هي احتمالات من نموذج الذكاء الاصطناعي.',
    'Percentage of maximum intensity for each category.': 'النسبة المئوية للشدة القصوى لكل فئة.',
    'AI Text Analysis': 'تحليل النص بالذكاء الاصطناعي',
    'Personalized Tips': 'نصائح مخصصة',
    'Based on your recent assessment, we suggest these activities:': 'بناءً على تقييمك، نقترح هذه الأنشطة:',
    'Helpful Resources': 'موارد مفيدة',
    'Reach out now:': 'تواصل الآن:',
    'Your responses indicate you may need immediate support. Please contact a mental health professional or crisis helpline.': 'تشير إجاباتك إلى أنك قد تحتاج إلى دعم فوري.',
    'Journal Access': 'الوصول للمذكرات',
    'Please enter your account password to open your private journal.': 'يرجى إدخال كلمة مرور حسابك لفتح مذكراتك.',
    'Incorrect password': 'كلمة المرور غير صحيحة',
    'Unlock': 'فتح',
    'This will remove the entry permanently.': 'سيؤدي هذا إلى إزالة المذكرة نهائيًا.',
    'Journal entry saved privately.': 'تم حفظ المذكرة بسرية.',
    'Save Reflection': 'حفظ التأمل',
    'Please write how you feel before submitting.': 'يرجى كتابة ما تشعر به أولاً.',
    'No assessments yet': 'لا توجد تقييمات بعد',
    'Complete a DASS-42 assessment to see your progress here.': 'أكمل تقييم DASS-42 لرؤية تقدمك هنا.',
    'DASS 42 Assessment History': 'سجل تقييم DASS 42',
    'AI Summary': 'ملخص الذكاء الاصطناعي',
    'Mini Games': 'ألعاب خفيفة',
    'Psychoeducation': 'تثقيف نفسي',
    'Professional Guidance': 'توجيه مهني',
    'Personalized for you': 'مخصص لك',
    'Quick Brief': 'موجز سريع',
    'Quick Examples (Tap to paste):': 'أمثلة سريعة (انقر للنسخ):',
    '"You don\'t have to control your thoughts. You just have to stop letting them control you."': '"لست مضطراً للسيطرة على أفكارك. عليك فقط التوقف عن السماح لها بالسيطرة عليك."',
    '— Dan Millman': '— دان ميلمان',
    'Friend': 'صديق',
    'User': 'مستخدم',
    'Name': 'الاسم',
    'Email': 'البريد الإلكتروني',
    'Reset Password': 'إعادة تعيين كلمة المرور',
    'Full\nAssessment': 'تقييم\nشامل',
    'Daily\nCheck-In': 'تقييم\nيومي',
    'Done\nToday': 'مكتمل\nاليوم',
    'Log\nMood': 'سجل\nالمزاج',
    'See all': 'عرض الكل',
    'Did not apply to me at all': 'لم ينطبق علي إطلاقاً',
    'Applied to me to some degree': 'انطبق علي إلى حد ما',
    'Applied to me to a considerable degree': 'انطبق علي بدرجة كبيرة',
    'Applied to me very much': 'انطبق علي كثيراً جداً',
    'Reflection': 'تأمل',
    'Question': 'سؤال',
    'of': 'من',
    'Type how you feel...': 'اكتب بماذا تشعر...',
    'Academic Stress': 'ضغوط أكاديمية',
    'I haven’t been focusing on my studies lately. Most of my time is spent on my phone, scrolling through social media or playing games instead of studying and finishing my work. Because of that, I’ve been wasting a lot of time and not paying enough attention to my lessons or assignments. My grades have become really bad, and I feel disappointed in myself because I know I could do much better if I managed my time and focused more on studying.': 'لم أركز في دراستي مؤخراً. أقضي معظم وقتي على الهاتف وأشعر بخيبة أمل في نفسي.',
    'Work Burnout': 'إرهاق العمل',
    'Work has been overwhelming. I feel like I\'m constantly drowning in tasks and I can\'t catch a break. Even when I log off, I\'m still thinking about emails I need to answer. I feel exhausted, unmotivated, and completely drained of energy.': 'لقد كان العمل مرهقاً. أشعر وكأنني أغرق باستمرار في المهام.',
    'Social Anxiety': 'قلق اجتماعي',
    'I\'ve been feeling really isolated lately, but at the same time, the thought of going out and being around people makes me extremely anxious and nervous. I worry too much about what others think of me and feel like everyone is judging me.': 'كنت أشعر بالعزلة مؤخراً، والتفكير في الخروج يجعلني قلقاً للغاية.',
    'Please enter a valid email address': 'يرجى إدخال بريد إلكتروني صحيح',
    'you must enter the Email': 'يجب إدخال البريد الإلكتروني',
    'you must enter the Password': 'يجب إدخال كلمة المرور',
    'Please enter a valid email to reset password': 'يرجى إدخال بريد إلكتروني صحيح لإعادة تعيين كلمة المرور',
    'Password': 'كلمة المرور',
    'Don\'t have an account?': 'ليس لديك حساب؟',
    'Continue with Google': 'المتابعة باستخدام Google',
    'Create account': 'إنشاء حساب',
    'you must enter the Name': 'يجب إدخال الاسم',
    'I found myself getting upset by quite trivial things.': 'كنت أجد نفسي منزعجاً بسبب أشياء بسيطة جداً.',
    'I was aware of dryness of my mouth.': 'كنت ألاحظ جفاف فمي.',
    'I couldn\'t seem to experience any positive feeling at all.': 'لم أكن أستطيع أن أشعر بأي شعور إيجابي على الإطلاق.',
    'I experienced breathing difficulty (eg, excessively rapid breathing, breathlessness in the absence of physical exertion).': 'كنت أعاني من صعوبة في التنفس، مثل التنفس السريع أو ضيق النفس دون مجهود بدني.',
    'I just couldn\'t seem to get going.': 'لم أكن أستطيع أن أبدأ في فعل أي شيء.',
    'I tended to over-react to situations.': 'كنت أميل إلى المبالغة في رد الفعل تجاه المواقف.',
    'I had a feeling of shakiness (eg, legs going to give way).': 'كنت أشعر بالارتجاف، مثل أن ساقيّ قد لا تحمِلاني.',
    'I found it difficult to relax.': 'كان من الصعب علي أن أسترخي.',
    'I found myself in situations that made me so anxious I was most relieved when they ended.': 'وجدت نفسي في مواقف جعلتني أشعر بقلق شديد ولم أكن أرتاح إلا عندما تنتهي.',
    'I felt that I had nothing to look forward to.': 'شعرت أنني لا أملك شيئاً أتطلع إليه.',
    'I found myself getting upset rather easily.': 'وجدت نفسي أنزعج بسهولة.',
    'I felt that I was using a lot of nervous energy.': 'شعرت أنني أستهلك الكثير من الطاقة العصبية.',
    'I felt sad and depressed.': 'شعرت بالحزن والاكتئاب.',
    'I found myself getting impatient when I was delayed in any way (eg, elevators, traffic lights, being kept waiting).': 'كنت أفقد صبري عندما أتأخر بأي شكل، مثل المصاعد أو إشارات المرور أو الانتظار.',
    'I had a feeling of faintness.': 'شعرت بالدوخة أو الإغماء.',
    'I felt that I had lost interest in just about everything.': 'شعرت أنني فقدت الاهتمام تقريباً بكل شيء.',
    'I felt I wasn\'t worth much as a person.': 'شعرت أنني لا أساوي الكثير كشخص.',
    'I felt that I was rather touchy.': 'شعرت أنني سريع الانفعال أو الحساسية.',
    'I perspired noticeably (eg, hands sweaty) in the absence of high temperatures or physical exertion.': 'كنت أتعرق بشكل ملحوظ، مثل تعرق اليدين، دون حرارة عالية أو مجهود بدني.',
    'I felt scared without any good reason.': 'شعرت بالخوف دون سبب واضح.',
    'I felt that life wasn\'t worthwhile.': 'شعرت أن الحياة لا تستحق العيش.',
    'I found it hard to wind down.': 'كان من الصعب علي أن أهدأ أو أسترخى.',
    'I had difficulty in swallowing.': 'واجهت صعوبة في البلع.',
    'I couldn\'t seem to get any enjoyment out of the things I did.': 'لم أكن أستطيع أن أستمتع بأي شيء أفعله.',
    'I was aware of the action of my heart in the absence of physical exertion (eg, sense of heart rate increase, heart missing a beat).': 'كنت ألاحظ نبض قلبي دون مجهود بدني، مثل تسارع النبض أو خفقان القلب.',
    'I felt down-hearted and blue.': 'شعرت بالكآبة والحزن.',
    'I found that I was very irritable.': 'وجدت أنني كنت سريع الانفعال جداً.',
    'I felt I was close to panic.': 'شعرت أنني كنت على وشك نوبة هلع.',
    'I found it hard to calm down after something upset me.': 'كان من الصعب علي أن أهدأ بعد شيء أزعجني.',
    'I feared that I would be "thrown" by some trivial but unfamiliar task.': 'كنت أخشى أن أربك بسبب مهمة بسيطة لكنها غير مألوفة.',
    'I was unable to become enthusiastic about anything.': 'لم أكن قادراً على الحماس لأي شيء.',
    'I found it difficult to tolerate interruptions to what I was doing.': 'كان من الصعب علي أن أتحمل المقاطعات أثناء قيامي بما أفعله.',
    'I was in a state of nervous tension.': 'كنت في حالة توتر عصبي.',
    'I felt I was pretty worthless.': 'شعرت أنني عديم القيمة تقريباً.',
    'I was intolerant of anything that kept me from getting on with what I was doing.': 'كنت لا أتحمل أي شيء يمنعني من مواصلة ما أفعله.',
    'I felt terrified.': 'شعرت بالرعب.',
    'I could see nothing in the future to be hopeful about.': 'لم أستطع أن أرى في المستقبل شيئاً يدعو للأمل.',
    'I felt that life was meaningless.': 'شعرت أن الحياة بلا معنى.',
    'I found myself getting agitated.': 'وجدت نفسي أشعر بالانفعال والاضطراب.',
    'I was worried about situations in which I might panic and make a fool of myself.': 'كنت أقلق من مواقف قد أتعرض فيها للذعر وأبدو بمظهر محرج.',
    'I experienced trembling (eg, in the hands).': 'كنت أعاني من الارتعاش، مثل ارتعاش اليدين.',
    'I found it difficult to work up the initiative to do things.': 'كان من الصعب علي أن أجد الدافع لفعل الأشياء.',
  };
}

extension LocalizationExtension on String {
  String get tr => Loc.tr(this);
}
